export const phoneMasks = [
    { mask: "+247 ####", code: "sh" },
    { mask: "+290 ####", code: "sh" },
    { mask: "+290 ####", code: "sh" },
    { mask: "+683 ####", code: "nu" },
    { mask: "+690 ####", code: "tk" },
    { mask: "+500 #####", code: "fk" },
    { mask: "+676 #####", code: "to" },
    { mask: "+677 #####", code: "sb" },
    { mask: "+678 #####", code: "vu" },
    { mask: "+688 2####", code: "tv" },
    { mask: "+49 ### ###", code: "de" },
    { mask: "+682 ## ###", code: "ck" },
    { mask: "+686 ## ###", code: "ki" },
    { mask: "+688 90####", code: "tv" },
    { mask: "+95 ### ###", code: "mm" },
    { mask: "+298 ### ###", code: "fo" },
    { mask: "+376 ### ###", code: "ad" },
    { mask: "+387 ## ####", code: "ba" },
    { mask: "+508 ## ####", code: "pm" },
    { mask: "+597 ### ###", code: "sr" },
    { mask: "+672 1## ###", code: "aq" },
    { mask: "+672 3## ###", code: "nf" },
    { mask: "+681 ## ####", code: "wf" },
    { mask: "+685 ## ####", code: "ws" },
    { mask: "+687 ## ####", code: "nc" },
    { mask: "+850 ### ###", code: "kp" },
    { mask: "+230 ### ####", code: "mu" },
    { mask: "+239 ## #####", code: "st" },
    { mask: "+245 # ######", code: "gw" },
    { mask: "+246 ### ####", code: "io" },
    { mask: "+263 # ######", code: "zw" },
    { mask: "+269 ## #####", code: "km" },
    { mask: "+297 ### ####", code: "aw" },
    { mask: "+299 ## ## ##", code: "gl" },
    { mask: "+354 ### ####", code: "is" },
    { mask: "+372 ### ####", code: "ee" },
    { mask: "+387 ## #####", code: "ba" },
    { mask: "+49 ### ## ##", code: "de" },
    { mask: "+501 ### ####", code: "bz" },
    { mask: "+507 ### ####", code: "pa" },
    { mask: "+592 ### ####", code: "gy" },
    { mask: "+597 ### ####", code: "sr" },
    { mask: "+599 ### ####", code: "cw" },
    { mask: "+599 ### ####", code: "bq" },
    { mask: "+60 # ### ###", code: "my" },
    { mask: "+62 ## ### ##", code: "id" },
    { mask: "+65 #### ####", code: "sg" },
    { mask: "+670 ### ####", code: "tl" },
    { mask: "+673 ### ####", code: "bn" },
    { mask: "+674 ### ####", code: "nr" },
    { mask: "+677 ### ####", code: "sb" },
    { mask: "+678 ## #####", code: "vu" },
    { mask: "+679 ## #####", code: "fj" },
    { mask: "+680 ### ####", code: "pw" },
    { mask: "+689 ## ## ##", code: "pf" },
    { mask: "+691 ### ####", code: "fm" },
    { mask: "+692 ### ####", code: "mh" },
    { mask: "+95 # ### ###", code: "mm" },
    { mask: "+960 ### ####", code: "mv" },
    { mask: "+220 ### ## ##", code: "gm" },
    { mask: "+232 ## ######", code: "sl" },
    { mask: "+234 ## ### ##", code: "ng" },
    { mask: "+237 #### ####", code: "cm" },
    { mask: "+238 ### ## ##", code: "cv" },
    { mask: "+248 # ### ###", code: "sc" },
    { mask: "+252 # ### ###", code: "so" },
    { mask: "+252 # ### ###", code: "so" },
    { mask: "+265 1 ### ###", code: "mw" },
    { mask: "+291 # ### ###", code: "er" },
    { mask: "+350 ### #####", code: "gi" },
    { mask: "+356 #### ####", code: "mt" },
    { mask: "+372 #### ####", code: "ee" },
    { mask: "+373 #### ####", code: "md" },
    { mask: "+47 ### ## ###", code: "no" },
    { mask: "+49 ### ## ###", code: "de" },
    { mask: "+504 #### ####", code: "hn" },
    { mask: "+505 #### ####", code: "ni" },
    { mask: "+506 #### ####", code: "cr" },
    { mask: "+52 ## ## ####", code: "mx" },
    { mask: "+53 # ### ####", code: "cu" },
    { mask: "+599 9### ####", code: "cw" },
    { mask: "+60 ## ### ###", code: "my" },
    { mask: "+62 ## ### ###", code: "id" },
    { mask: "+64 ## ### ###", code: "nz" },
    { mask: "+66 ## ### ###", code: "th" },
    { mask: "+670 77# #####", code: "tl" },
    { mask: "+670 78# #####", code: "tl" },
    { mask: "+850 #### ####", code: "kp" },
    { mask: "+852 #### ####", code: "hk" },
    { mask: "+853 #### ####", code: "mo" },
    { mask: "+886 #### ####", code: "tw" },
    { mask: "+95 ## ### ###", code: "mm" },
    { mask: "+961 # ### ###", code: "lb" },
    { mask: "+965 #### ####", code: "kw" },
    { mask: "+967 # ### ###", code: "ye" },
    { mask: "+973 #### ####", code: "bh" },
    { mask: "+974 #### ####", code: "qa" },
    { mask: "+975 # ### ###", code: "bt" },
    { mask: "+1 ### ### ####", code: "us" },
    { mask: "+1 242 ### ####", code: "bs" },
    { mask: "+1 246 ### ####", code: "bb" },
    { mask: "+1 264 ### ####", code: "ai" },
    { mask: "+1 268 ### ####", code: "ag" },
    { mask: "+1 284 ### ####", code: "vg" },
    { mask: "+1 340 ### ####", code: "vi" },
    { mask: "+1 345 ### ####", code: "ky" },
    { mask: "+1 441 ### ####", code: "bm" },
    { mask: "+1 473 ### ####", code: "gd" },
    { mask: "+1 649 ### ####", code: "tc" },
    { mask: "+1 664 ### ####", code: "ms" },
    { mask: "+1 670 ### ####", code: "mp" },
    { mask: "+1 671 ### ####", code: "gu" },
    { mask: "+1 684 ### ####", code: "as" },
    { mask: "+1 721 ### ####", code: "sx" },
    { mask: "+1 758 ### ####", code: "lc" },
    { mask: "+1 767 ### ####", code: "dm" },
    { mask: "+1 784 ### ####", code: "vc" },
    { mask: "+1 809 ### ####", code: "do" },
    { mask: "+1 829 ### ####", code: "do" },
    { mask: "+1 849 ### ####", code: "do" },
    { mask: "+1 868 ### ####", code: "tt" },
    { mask: "+1 869 ### ####", code: "kn" },
    { mask: "+1 876 ### ####", code: "jm" },
    { mask: "+216 ## ### ###", code: "tn" },
    { mask: "+218 ## ### ###", code: "ly" },
    { mask: "+222 ## ## ####", code: "mr" },
    { mask: "+223 ## ## ####", code: "ml" },
    { mask: "+224 ## ### ###", code: "gn" },
    { mask: "+225 ## ### ###", code: "ci" },
    { mask: "+226 ## ## ####", code: "bf" },
    { mask: "+227 ## ## ####", code: "ne" },
    { mask: "+228 ## ### ###", code: "tg" },
    { mask: "+229 ## ## ####", code: "bj" },
    { mask: "+231 ## ### ###", code: "lr" },
    { mask: "+234 ## ### ###", code: "ng" },
    { mask: "+236 ## ## ####", code: "cf" },
    { mask: "+241 # ## ## ##", code: "ga" },
    { mask: "+252 ## ### ###", code: "so" },
    { mask: "+254 ### ######", code: "ke" },
    { mask: "+257 ## ## ####", code: "bi" },
    { mask: "+258 ## ### ###", code: "mz" },
    { mask: "+262 ##### ####", code: "re" },
    { mask: "+266 # ### ####", code: "ls" },
    { mask: "+267 ## ### ###", code: "bw" },
    { mask: "+268 ## ## ####", code: "sz" },
    { mask: "+27 ## ### ####", code: "za" },
    { mask: "+31 ## ### ####", code: "nl" },
    { mask: "+32 ### ### ###", code: "be" },
    { mask: "+33 ### ### ###", code: "fr" },
    { mask: "+34 ### ### ###", code: "es" },
    { mask: "+357 ## ### ###", code: "cy" },
    { mask: "+36 ### ### ###", code: "hu" },
    { mask: "+370 ### ## ###", code: "lt" },
    { mask: "+371 ## ### ###", code: "lv" },
    { mask: "+374 ## ### ###", code: "am" },
    { mask: "+377 ## ### ###", code: "mc" },
    { mask: "+382 ## ### ###", code: "me" },
    { mask: "+385 ## ### ###", code: "hr" },
    { mask: "+386 ## ### ###", code: "si" },
    { mask: "+389 ## ### ###", code: "mk" },
    { mask: "+39 6 698 #####", code: "va" },
    { mask: "+40 ## ### ####", code: "ro" },
    { mask: "+41 ## ### ####", code: "ch" },
    { mask: "+45 ## ## ## ##", code: "dk" },
    { mask: "+46 ## ### ####", code: "se" },
    { mask: "+48 ### ### ###", code: "pl" },
    { mask: "+49 ### ## ####", code: "de" },
    { mask: "+502 # ### ####", code: "gt" },
    { mask: "+503 ## ## ####", code: "sv" },
    { mask: "+509 ## ## ####", code: "ht" },
    { mask: "+51 ### ### ###", code: "pe" },
    { mask: "+56 # #### ####", code: "cl" },
    { mask: "+591 # ### ####", code: "bo" },
    { mask: "+593 # ### ####", code: "ec" },
    { mask: "+594 ##### ####", code: "gf" },
    { mask: "+60 ## ### ####", code: "my" },
    { mask: "+60 ### ### ###", code: "my" },
    { mask: "+61 # #### ####", code: "au" },
    { mask: "+62 ## ### ####", code: "id" },
    { mask: "+62 8## ### ###", code: "id" },
    { mask: "+64 ### ### ###", code: "nz" },
    { mask: "+66 ## ### ####", code: "th" },
    { mask: "+675 ### ## ###", code: "pg" },
    { mask: "+81 ### ### ###", code: "jp" },
    { mask: "+82 ## ### ####", code: "kr" },
    { mask: "+84 ## #### ###", code: "vn" },
    { mask: "+850 ## ### ###", code: "kp" },
    { mask: "+855 ## ### ###", code: "kh" },
    { mask: "+856 ## ### ###", code: "la" },
    { mask: "+880 ## ### ###", code: "bd" },
    { mask: "+93 ## ### ####", code: "af" },
    { mask: "+94 ## ### ####", code: "lk" },
    { mask: "+961 ## ### ###", code: "lb" },
    { mask: "+966 # ### ####", code: "sa" },
    { mask: "+967 ## ### ###", code: "ye" },
    { mask: "+968 ## ### ###", code: "om" },
    { mask: "+971 # ### ####", code: "ae" },
    { mask: "+972 # ### ####", code: "il" },
    { mask: "+975 17 ### ###", code: "bt" },
    { mask: "+976 ## ## ####", code: "mn" },
    { mask: "+977 ## ### ###", code: "np" },
    { mask: "+993 # ### ####", code: "tm" },
    { mask: "+20 ### ### ####", code: "eg" },
    { mask: "+211 ## ### ####", code: "ss" },
    { mask: "+212 ## #### ###", code: "ma" },
    { mask: "+213 ## ### ####", code: "dz" },
    { mask: "+218 21 ### ####", code: "ly" },
    { mask: "+221 ## ### ####", code: "sn" },
    { mask: "+233 ### ### ###", code: "gh" },
    { mask: "+235 ## ## ## ##", code: "td" },
    { mask: "+240 ## ### ####", code: "gq" },
    { mask: "+242 ## ### ####", code: "cg" },
    { mask: "+243 ### ### ###", code: "cd" },
    { mask: "+244 ### ### ###", code: "ao" },
    { mask: "+249 ## ### ####", code: "sd" },
    { mask: "+250 ### ### ###", code: "rw" },
    { mask: "+251 ## ### ####", code: "et" },
    { mask: "+253 ## ## ## ##", code: "dj" },
    { mask: "+255 ## ### ####", code: "tz" },
    { mask: "+256 ### ### ###", code: "ug" },
    { mask: "+260 ## ### ####", code: "zm" },
    { mask: "+261 ## ## #####", code: "mg" },
    { mask: "+264 ## ### ####", code: "na" },
    { mask: "+265 # #### ####", code: "mw" },
    { mask: "+30 ### ### ####", code: "gr" },
    { mask: "+351 ## ### ####", code: "pt" },
    { mask: "+352 ### ### ###", code: "lu" },
    { mask: "+353 ### ### ###", code: "ie" },
    { mask: "+355 ### ### ###", code: "al" },
    { mask: "+359 ### ### ###", code: "bg" },
    { mask: "+377 ### ### ###", code: "mc" },
    { mask: "+378 #### ######", code: "sm" },
    { mask: "+381 ## ### ####", code: "rs" },
    { mask: "+39 ### #### ###", code: "it" },
    { mask: "+420 ### ### ###", code: "cz" },
    { mask: "+421 ### ### ###", code: "sk" },
    { mask: "+43 ### ### ####", code: "at" },
    { mask: "+44 ## #### ####", code: "gb" },
    { mask: "+49 ### ### ####", code: "de" },
    { mask: "+52 ### ### ####", code: "mx" },
    { mask: "+54 ### ### ####", code: "ar" },
    { mask: "+55 ## #### ####", code: "br" },
    { mask: "+55 ## 7### ####", code: "br" },
    { mask: "+57 ### ### ####", code: "co" },
    { mask: "+58 ### ### ####", code: "ve" },
    { mask: "+590 ### ### ###", code: "gp" },
    { mask: "+593 ## ### ####", code: "ec" },
    { mask: "+595 ### ### ###", code: "py" },
    { mask: "+598 # ### ## ##", code: "uy" },
    { mask: "+62 8## ### ####", code: "id" },
    { mask: "+63 ### ### ####", code: "ph" },
    { mask: "+64 ### ### ####", code: "nz" },
    { mask: "+7 ### ### ####", code: "kz" },
    { mask: "+7 6## ### ## ##", code: "kz" },
    { mask: "+7 7## ### ## ##", code: "kz" },
    { mask: "+7 9## ### ## ##", code: "ru" },
    { mask: "+81 ## #### ####", code: "jp" },
    { mask: "+84 ### #### ###", code: "vn" },
    { mask: "+86 ### #### ###", code: "cn" },
    { mask: "+886 # #### ####", code: "tw" },
    { mask: "+90 ### ### ####", code: "tr" },
    { mask: "+91 #### ### ###", code: "in" },
    { mask: "+92 ### ### ####", code: "pk" },
    { mask: "+962 # #### ####", code: "jo" },
    { mask: "+963 ## #### ###", code: "sy" },
    { mask: "+966 5 #### ####", code: "sa" },
    { mask: "+967 ### ### ###", code: "ye" },
    { mask: "+970 ## ### ####", code: "ps" },
    { mask: "+971 5# ### ####", code: "ae" },
    { mask: "+972 5# ### ####", code: "il" },
    { mask: "+98 ### ### ####", code: "ir" },
    { mask: "+992 ## ### ####", code: "tj" },
    { mask: "+995 ### ### ###", code: "ge" },
    { mask: "+996 ### ### ###", code: "kg" },
    { mask: "+998 ## ### ####", code: "uz" },
    { mask: "+234 ### ### ####", code: "ng" },
    { mask: "+375 ## ### ## ##", code: "by" },
    { mask: "+380 ## ### ## ##", code: "ua" },
    { mask: "+423 ### ### ####", code: "li" },
    { mask: "+49 #### ### ####", code: "de" },
    { mask: "+55 ## 9#### ####", code: "br" },
    { mask: "+596 ### ## ## ##", code: "mq" },
    { mask: "+850 ### #### ###", code: "kp" },
    { mask: "+850 191 ### ####", code: "kp" },
    { mask: "+856 20## ### ###", code: "la" },
    { mask: "+86 ### #### ####", code: "cn" },
    { mask: "+964 ### ### ####", code: "iq" },
    { mask: "+994 ## ### ## ##", code: "az" },
    { mask: "+358 ### ### ## ##", code: "fi" },
    { mask: "+62 8## ### ## ###", code: "id" },
    { mask: "+86 ## ##### #####", code: "cn" },
    { mask: "+850 #### #############", code: "kp" }
];
